import 'dotenv/config'
import postgres from 'postgres'

async function syncTables() {
  const sql = postgres({
    host: process.env.DB_HOST || '103.193.145.61',
    port: Number(process.env.DB_PORT || 6881),
    username: process.env.DB_USER || 'postgres',
    password: process.env.DB_PASSWORD || '',
    database: process.env.DB_NAME || 'inl_portal',
  })

  console.log('🔄 Synchronizing PostgreSQL database tables & schema...')

  try {
    // 1. Add revised to document_audit_action enum if missing
    await sql`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM pg_enum
          WHERE enumlabel = 'revised'
            AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'document_audit_action')
        ) THEN
          ALTER TYPE document_audit_action ADD VALUE 'revised';
        END IF;
      END $$;
    `
    console.log('✅ Checked document_audit_action enum.')

    // 2. Create document_versions table if not exists (UUID generated by Node application layer)
    await sql`
      CREATE TABLE IF NOT EXISTS document_versions (
        id UUID PRIMARY KEY,
        document_id UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
        version INTEGER NOT NULL,
        file_path VARCHAR(500) NOT NULL,
        file_size INTEGER NOT NULL,
        mime_type VARCHAR(150) NOT NULL,
        changelog TEXT,
        uploaded_by UUID NOT NULL REFERENCES employee(id) ON DELETE RESTRICT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `
    console.log('✅ Created table document_versions (if not exists).')

    // 3. Create indexes for document_versions
    await sql`
      CREATE INDEX IF NOT EXISTS document_versions_document_idx ON document_versions(document_id, version);
    `
    await sql`
      CREATE UNIQUE INDEX IF NOT EXISTS document_versions_doc_ver_uidx ON document_versions(document_id, version);
    `
    console.log('✅ Created indexes for document_versions.')

    // 4. Backfill v1 into document_versions for any existing documents that don't have a v1 record yet
    await sql`
      INSERT INTO document_versions (id, document_id, version, file_path, file_size, mime_type, changelog, uploaded_by, created_at)
      SELECT md5(random()::text || clock_timestamp()::text)::uuid, d.id, d.version, d.file_path, d.file_size, d.mime_type, 'Versi awal dokumen (v1)', d.uploaded_by, d.created_at
      FROM documents d
      WHERE NOT EXISTS (
        SELECT 1 FROM document_versions v WHERE v.document_id = d.id AND v.version = d.version
      );
    `
    console.log('✅ Backfilled initial versions for existing documents.')

    console.log('🎉 Database synchronization complete!')
  } catch (error) {
    console.error('❌ Error synchronizing database:', error)
    process.exit(1)
  } finally {
    await sql.end()
  }
}

syncTables()
